### ISSUE TITLE
image stretching

### ISSUE THREAD

**Issue by chu-shen** [hibikikuze4dan/lanraragi-react-web#4]
[display method fill](https://github.com/hibikikuze4dan/lanraragi-react-web/blob/f5920a4ed6a7a2dbbcc916841bd1ffa8fb2dd16f/src/components/image/image.js#L60) was hard-coded, resulting in image stretching

A fix PR #3  has been submitted to remove the hard-coded 'fill' and provide settings for contain, cover, and fill

**Comment by hibikikuze4dan** [comment]
Thanks for the PR! If possible, could you please provide a screenshot or some other kind of example of the problem you faced that led you to create this PR?

The hard-coded fill and resulting image stretching was intentional. On smaller viewports, wider images like in CG sets can be hard to read and the fill property helped with that, but I can see why someone would want another option for viewing an archive's images. At the same time though, that option should be separate from the display method for the thumbnails. The cover option is also a pretty detrimental viewing experience for wider images in smaller viewports.

**Comment by chu-shen** [comment]
PR-contain like Webtoon reading mode in [Tachiyomi](https://tachiyomi.org/help/guides/reader-settings/#default-reading-mode)

I believe it is important to maintain the aspect ratio of the image to ensure that it does not distort. So i add the contain display method

There is no objection to separating the display modes for thumbnail and archive. But perhaps those who can accept the archive display method can also accept the same display method for thumbnail.

<details>
  <summary>screenshot</summary>

![PqjhXLOrZF](https://github.com/hibikikuze4dan/lanraragi-react-web/assets/45256288/7388a478-3caa-43f0-b0f9-f3dbd1c0a927)
![gIYk2triOQ](https://github.com/hibikikuze4dan/lanraragi-react-web/assets/45256288/1802ae3f-9f6c-4fdd-b8f7-7495a0ba4f8b)
</details>

**Comment by hibikikuze4dan** [comment]
Just pushed up an update and added the setting. Should basically work the same as your PR. The Cover display method is still shot, but that can be fixed later.

**Comment by chu-shen** [comment]
work well for me👍

---

What about another PR #1? This PR adds authorization for 'delete archive' and 'update category'
